plugins {
    id 'org.jetbrains.intellij' version '1.17.3'
    id 'java'
}

// 指定版本文件的路径
def versionFile = file('hotswap-agent/src/main/resources/version.txt')

group 'com.coderevolt'
version versionFile.text.trim()

repositories {
    mavenLocal()
    maven {
        url 'https://maven.aliyun.com/repository/public/'
    }
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

// 设置兼容性版本
sourceCompatibility = '1.8'
targetCompatibility = '1.8'

dependencies {
//    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
//    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation(project(":hotswap-common"))
    implementation(project(":hotswap-api"))
    implementation(project(":hotswap-rpc"))
    compileOnly(files("hotswap-agent/libs/tools.jar"))
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version = '2021.3.3'
}
patchPluginXml {
    sinceBuild = "203"
//    包含未来所有版本分支
    untilBuild = ""
    changeNotes = """
    <b>版本1.0</b>
    <ol>
        <li>支持SpringBoot、Mybatis、Mybatis-plus的环境下实现MapperXml的热更新</li>
        <li>支持MapperXml方法体修改、新增、删除、resultMap、sql片段等的热更新</li>
    </ol>
    
    <b>版本1.5</b>
    <ol>
        <li>支持class方法热更新</li>
        <li>验证static方法、对象方法、内部类方法热更新</li>
    </ol>
    
    <b>版本1.6</b>
    <ol>
        <li>支持指定单个项目热更新</li>
        <li>修复了一些已知bug</li>
    </ol>
    
    <b>版本1.7</b>
    <ol>
        <li>去除多余jar，插件瘦身</li>
        <li>修复了一些已知bug</li>
        <li>idea进程崩溃修复</li>
    </ol>
    
    <b>版本1.8</b>
    <ol>
        <li>class方法热更新支持lombok</li>
        <li>更新获取pid的方式</li>
        <li>多线程参数优化</li>
        <li>================1.8.1================</li>
        <li>添加插件日志收集</li>
        <li>支持动态编译新增类</li>
    </ol>
    
    <b>版本1.9</b>
     <ol>
        <li>支持spring热更新（注册、销毁、动态mapping)</li>
        <li>修复已知存在问题</li>
        <li>================1.9.1================</li>
        <li>静态agent注入，相对于动态注入更稳定</li>
        <li>设置RPC守护线程，不影响进程结束优化</li>
        <li>================1.9.2================</li>
        <li>解决多模块mapper更新bug</li>
        <li>解决StrictMap替换mp兼容</li>
        <li>================1.9.3================</li>
        <li>动态编译兼容jarManifest启动</li>
    </ol>
    
    <b>版本2.0</b>
     <ol>
        <li>优化IDEA文件自动保存问题</li>
        <li>支持.class文件和Jar包内文件热更新</li>
        <li>修复已知问题</li>
    </ol>
    """
}
test {
    useJUnitPlatform()
}